apiVersion: apps/v1
kind: Deployment
metadata:
  name: roxo-serv-customer-deployment
  labels:
    app: roxo-serv-customer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: roxo-serv-customer
  template:
    metadata:
      labels:
        app: roxo-serv-customer
    spec:
      containers:
        - name: roxo-serv-customer
          image: guilheag/roxo-serv-customer
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env: # Setting Enviornmental Variables
            - name: DB_HOST   # Setting Database host address from configMap
              valueFrom:
                configMapKeyRef:
                  name: roxo-serv-customer-db-config
                  key: host

            - name: DB_NAME  # Setting Database name from configMap
              valueFrom:
                configMapKeyRef:
                  name: roxo-serv-customer-db-config
                  key: dbName

            - name: DB_USERNAME  # Setting Database username from Secret
              valueFrom:
                secretKeyRef:
                  name: roxo-serv-customer-mysql-secrets
                  key: username

            - name: DB_PASSWORD # Setting Database password from Secret
              valueFrom:
                secretKeyRef:
                  name: roxo-serv-customer-mysql-secrets
                  key: password
---
apiVersion: v1
kind: Service
metadata:
  name: roxo-serv-customer
spec:
  type: NodePort
  selector:
    app: roxo-serv-customer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30105