apiVersion: apps/v1
kind: Deployment
metadata:
  name: roxo-serv-product-deployment
spec:
  selector:
    matchLabels:
      app: roxo-serv-product-mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: roxo-serv-product-mysql
    spec:
      containers:
        - name: roxo-serv-product
          image: roxo-serv-product:1.0
          ports:
            - containerPort: 8080
          env:   # Setting Enviornmental Variables
            - name: DB_HOST   # Setting Database host address from configMap
              value: mysql
            - name: DB_NAME  # Setting Database name from configMap
              value: javatechie
            - name: DB_USERNAME  # Setting Database username from Secret
              value:  root
            - name: DB_PASSWORD # Setting Database password from Secret
              value: root

---

apiVersion: v1 # Kubernetes API version
kind: Service # Kubernetes resource kind we are creating
metadata: # Metadata of the resource kind we are creating
  name: roxo-serv-product-svc
spec:
  selector:
    app: roxo-serv-product-mysql
  ports:
    - protocol: "TCP"
      port: 8080 # The port that the service is running on in the cluster
      targetPort: 8080 # The port exposed by the service
  type: NodePort # type of the service.